CREATE DATABASE Compugraf

GO

USE [Compugraf]

GO


CREATE TABLE [dbo].[TB_PESSOA](
	[ID] [bigint] IDENTITY(1,1) Primary key NOT NULL ,
	[NOME] [nvarchar](50) NOT NULL,
	[SOBRENOME] [nvarchar](100) NOT NULL,
	[NACIONALIDADE] [nvarchar](100) NULL,
	[CEP] [nvarchar](9) NOT NULL,
	[ESTADO] [nvarchar] (100) NULL,
	[CIDADE] [nvarchar] (100) NULL,
	[LOGRADOURO] [nvarchar] (150) NULL,
	[EMAIL] [nvarchar] (100) NULL,
	[TELEFONE] [nvarchar](10) NULL
	)

GO


CREATE PROCEDURE [dbo].[STP_SEL_PESSOA]
    @NOME nvarchar(50) = NULL,
	@SOBRENOME nvarchar(100) = NULL,
	@NACIONALIDADE nvarchar(100) = NULL,
	@CEP nvarchar(9) = NULL,
	@ESTADO nvarchar(100) = NULL,
	@CIDADE nvarchar(100) = NULL,
	@LOGRADOURO nvarchar(150) = NULL,
	@EMAIL nvarchar(100) = NULL,
	@TELEFONE nvarchar(10) = NULL
AS
BEGIN

   SELECT * FROM TB_PESSOA
   WHERE 
      (@NOME IS NULL OR NOME LIKE '%' + @NOME + '%') AND
	  (@SOBRENOME IS NULL OR SOBRENOME LIKE '%' + @SOBRENOME + '%') AND
	  (@NACIONALIDADE IS NULL OR NACIONALIDADE LIKE '%' + @NACIONALIDADE + '%') AND
	  (@CEP IS NULL OR CEP LIKE '%' + @CEP + '%') AND
	  (@ESTADO IS NULL OR ESTADO LIKE '%' + @ESTADO + '%') AND
	  (@CIDADE IS NULL OR CIDADE LIKE '%' + @CIDADE + '%') AND
	  (@LOGRADOURO IS NULL OR LOGRADOURO LIKE '%' + @LOGRADOURO + '%') AND
	  (@EMAIL IS NULL OR EMAIL LIKE '%' + @EMAIL + '%') AND
	  (@TELEFONE IS NULL OR TELEFONE LIKE '%' + @TELEFONE +'%')
END

GO


CREATE PROCEDURE [dbo].[STP_INS_PESSOA]

	@NOME nvarchar(50) = NULL,
	@SOBRENOME nvarchar(100) = NULL,
	@NACIONALIDADE nvarchar(100) = NULL,
	@CEP nvarchar(9) = NULL,
	@ESTADO nvarchar(100) = NULL,
	@CIDADE nvarchar(100) = NULL,
	@LOGRADOURO nvarchar(150) = NULL,
	@EMAIL nvarchar(100) = NULL,
	@TELEFONE nvarchar(10) = NULL
	AS
BEGIN
	
   INSERT INTO TB_PESSOA (NOME, SOBRENOME, NACIONALIDADE, CEP, ESTADO, CIDADE, LOGRADOURO, EMAIL, TELEFONE)VALUES(@NOME, @SOBRENOME, @NACIONALIDADE, @CEP, @ESTADO, @CIDADE, @LOGRADOURO, @EMAIL, @TELEFONE)
END

GO

CREATE PROCEDURE [dbo].[STP_UPD_PESSOA]

    @ID bigint,
	@NOME nvarchar(50),
	@SOBRENOME nvarchar(100) = NULL,
	@NACIONALIDADE nvarchar(100) = NULL,
	@CEP nvarchar(9) = NULL,
	@ESTADO nvarchar(100) = NULL,
	@CIDADE nvarchar(100) = NULL,
	@LOGRADOURO nvarchar(150) = NULL,
	@EMAIL nvarchar(100) = NULL,
	@TELEFONE nvarchar(10) = NULL
	AS
BEGIN
   UPDATE TB_PESSOA SET NOME = @NOME, SOBRENOME = @SOBRENOME, NACIONALIDADE = @NACIONALIDADE, CEP = @CEP, ESTADO = @ESTADO, CIDADE = @CIDADE, LOGRADOURO =@LOGRADOURO, EMAIL = @EMAIL,  TELEFONE = @TELEFONE
   WHERE ID = @ID
END

GO

CREATE PROCEDURE [dbo].[STP_DEL_PESSOA]
    @ID bigint
	AS
BEGIN

   DELETE TB_PESSOA 
   WHERE ID = @ID
END

GO


CREATE PROCEDURE [dbo].[STP_SEL_PESSOA_ByID]
 @ID bigint
	AS

BEGIN

   SELECT * FROM TB_PESSOA
   WHERE ID = @ID
END

